-- TankstellenErtrag: datenschutzfreundliches Besuchertracking
-- Keine IP-Adresse, keine persistente Besucher-ID.
-- Ein Aufruf wird pro Browser-Session einmal gezählt.

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visited_at timestamptz not null default now(),
  referrer text,
  landing_path text,
  source text
);

create index if not exists site_visits_visited_at_idx
  on public.site_visits (visited_at);

create index if not exists site_visits_source_idx
  on public.site_visits (source);

alter table public.site_visits enable row level security;

drop policy if exists "Public can record anonymous site visits" on public.site_visits;
create policy "Public can record anonymous site visits"
  on public.site_visits
  for insert
  to anon, authenticated
  with check (
    length(coalesce(referrer,'')) <= 500
    and length(coalesce(landing_path,'')) <= 300
    and length(coalesce(source,'')) <= 50
  );

drop policy if exists "Admin can read site visits" on public.site_visits;
create policy "Admin can read site visits"
  on public.site_visits
  for select
  to authenticated
  using (
    lower(coalesce(auth.jwt()->>'email','')) = 'svenkrick@gmx.de'
  );

revoke all on public.site_visits from anon, authenticated;
grant insert on public.site_visits to anon, authenticated;
grant select on public.site_visits to authenticated;

create or replace function public.get_site_visitor_stats()
returns jsonb
language sql
security invoker
set search_path=''
as $$
  select jsonb_build_object(
    'today',
      (select count(*) from public.site_visits
       where visited_at >= date_trunc('day', now())),
    'last7',
      (select count(*) from public.site_visits
       where visited_at >= now() - interval '7 days'),
    'month',
      (select count(*) from public.site_visits
       where visited_at >= date_trunc('month', now())),
    'linkedin',
      (select count(*) from public.site_visits
       where visited_at >= date_trunc('month', now())
         and lower(coalesce(source,'')) = 'linkedin'),
    'applications',
      (select count(*) from public.pilot_applications
       where coalesce(lower(email),'') <> 'svenkrick@gmx.de')
  );
$$;

revoke all on function public.get_site_visitor_stats() from public;
revoke all on function public.get_site_visitor_stats() from anon;
grant execute on function public.get_site_visitor_stats() to authenticated;
